### ISSUE TITLE
can you provide me prog_emmc_ufs_firehose_Sdm660_ddr.elf file

### ISSUE THREAD

**Issue by yNeer** [rk779/android_kernel_asus_sdm660#1]
i have bricked my phone and current .elf file is not working can you provide me same file for asus zenfone max por m2

**Comment by yNeer** [comment]
Validating Application Configuration
Load APP Configuration
COM:22
PBLDOWNLOADPROTOCOL:0
PROGRAMMER:True
PROGRAMMER:D:\repair\Lenovo_A6020a40_S003_Q1021101_20170410\Firmware\validated_emmc_firehose_8936.mbn
RESETSAHARASTATEEMACHINE:False
SEARCHPATH:D:\repair\Lenovo_A6020a40_S003_Q1021101_20170410\Firmware
RAWPROGRAM:
rawprogram_unsparse.xml
PATCH:
patch0.xml
ACKRAWDATAEVERYNUMPACKETS:False
ACKRAWDATAEVERYNUMPACKETS:100
MAXPAYLOADSIZETOTARGETINBYTES:False
MAXPAYLOADSIZETOTARGETINBYTES:49152
DEVICETYPE:UFS
PLATFORM:8x26
VALIDATIONMODE:0
RESETAFTERDOWNLOAD:False
MAXDIGESTTABLESIZE:8192
SWITCHTOFIREHOSETIMEOUT:30
RESETTIMEOUT:200
RESETDELAYTIME:2
FLATBUILDPATH:C:\
FLATBUILDFORCEOVERRIDE:True
QCNPATH:C:\Temp\00000000.qcn
QCNAUTOBACKUPRESTORE:False
SPCCODE:000000
ENABLEMULTISIM:True
AUTOPRESERVEPARTITIONS:False
PARTITIONPRESERVEMODE:0
PRESERVEDPARTITIONS:0
PRESERVEDPARTITIONS:
ERASEALL:True
Load ARG Configuration
Validating Download Configuration
Image Search Path: D:\repair\Lenovo_A6020a40_S003_Q1021101_20170410\Firmware
RAWPROGRAM file path: D:\repair\Lenovo_A6020a40_S003_Q1021101_20170410\Firmware\rawprogram_unsparse.xml
PATCH file path:D:\repair\Lenovo_A6020a40_S003_Q1021101_20170410\Firmware\patch0.xml
Programmer Path:D:\repair\Lenovo_A6020a40_S003_Q1021101_20170410\Firmware\validated_emmc_firehose_8936.mbn
Process Index:0
Programmer Path:D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\prog_emmc_ufs_firehose_Sdm660_ddr.elf
Image Search Path: D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash
RAWPROGRAM file path: D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\rawprogram_unsparse.xml
PATCH file path:D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\patch0.xml
Image Search Path: D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash
RAWPROGRAM file path: D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\rawprogram_unsparse_no_fsg.xml
PATCH file path:D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\patch0.xml
Start Download
Program Path:D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\prog_emmc_ufs_firehose_Sdm660_ddr.elf
***** Working Folder:C:\Users\jainikcomputers\AppData\Roaming\Qualcomm\QFIL\COMPORT_22
Binary build date: Oct 31 2016 @ 22:51:05
QSAHARASERVER CALLED LIKE THIS: 'C:\Program Files\Qualcomm\QPST\bin\QSaharaServer.ex'Current working dir: C:\Users\jainikcomputers\AppData\Roaming\Qualcomm\QFIL\COMPORT_22
Sahara mappings:
2: amss.mbn
6: apps.mbn
8: dsp1.mbn
10: dbl.mbn
11: osbl.mbn
12: dsp2.mbn
16: efs1.mbn
17: efs2.mbn
20: efs3.mbn
21: sbl1.mbn
22: sbl2.mbn
23: rpm.mbn
25: tz.mbn
28: dsp3.mbn
29: acdb.mbn
30: wdt.mbn
31: mba.mbn
13: D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\prog_emmc_ufs_firehose_Sdm660_ddr.elf
15:33:34: Requested ID 13, file: "D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\prog_emmc_ufs_firehose_Sdm660_ddr.elf"
15:33:35: 624548 bytes transferred in 0.235000 seconds (2.5345MBps)
15:33:35: File transferred successfully
15:33:35: Sahara protocol completed
Sending Programmer Finished
Switch To FireHose
Wait for 3 seconds...
Max Payload Size to Target:49152 Bytes
Device Type:eMMC
Platform:8x26
Disable Ack Raw Data Every N Packets
Skip Write:False
Always Validate:False
Use Verbose:False
***** Working Folder:C:\Users\jainikcomputers\AppData\Roaming\Qualcomm\QFIL\COMPORT_22
Base Version: 16.10.28.15.28
Binary build date: Oct 31 2016 @ 22:51:02
Incremental Build version: 16.10.31.22.51.02
15:33:38: INFO: FH_LOADER WAS CALLED EXACTLY LIKE THIS
************************************************
C:\Program Files\Qualcomm\QPST\bin\fh_loader.exe --port=\\.\COM22 --sendxml=rawprogram_unsparse_no_fsg.xml --search_path=D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash --noprompt --showpercentagecomplete --maxpayloadsizeinbytes=49152 --zlpawarehost=1 --memoryname=emmc 
************************************************
15:33:38: INFO: Current working dir (cwd): C:\Users\jainikcomputers\AppData\Roaming\Qualcomm\QFIL\COMPORT_22\
15:33:38: INFO: Showing network mappings to allow debugging
15:33:38: INFO: 
15:33:38: INFO: Trying to store 'rawprogram_unsparse_no_fsg.xml' in string table
15:33:38: INFO: Looking for file 'rawprogram_unsparse_no_fsg.xml'
15:33:38: INFO: User wants to talk to port '\\.\COM22'
15:33:38: INFO: Took       0.00000000 seconds to open port
15:33:38: INFO: Sorting TAGS to ensure order is <configure>,<erase>, others, <patch>,<power>
15:33:38: INFO: If  you don't want this, use --dontsorttags
15:33:38: INFO: Looking for file 'xbl.elf'
15:33:38: INFO: Looking for file 'xbl.elf'
15:33:38: INFO: Looking for file 'tz.mbn'
15:33:38: INFO: Looking for file 'tz.mbn'
15:33:38: INFO: Looking for file 'rpm.mbn'
15:33:38: INFO: Looking for file 'rpm.mbn'
15:33:38: INFO: Looking for file 'hyp.mbn'
15:33:38: INFO: Looking for file 'hyp.mbn'
15:33:38: INFO: Looking for file 'pmic.elf'
15:33:38: INFO: Looking for file 'pmic.elf'
15:33:38: INFO: Looking for file 'system_1.img'
15:33:38: INFO: Looking for file 'system_2.img'
15:33:38: INFO: Looking for file 'system_3.img'
15:33:39: INFO: Looking for file 'system_4.img'
15:33:39: INFO: Looking for file 'system_5.img'
15:33:39: INFO: Looking for file 'system_6.img'
15:33:39: INFO: Looking for file 'system_7.img'
15:33:39: INFO: Looking for file 'system_8.img'
15:33:39: INFO: Looking for file 'system_9.img'
15:33:39: INFO: Looking for file 'system_10.img'
15:33:39: INFO: Looking for file 'system_11.img'
15:33:39: INFO: Looking for file 'system_12.img'
15:33:39: INFO: Looking for file 'system_13.img'
15:33:39: INFO: Looking for file 'system_14.img'
15:33:39: INFO: Looking for file 'system_15.img'
15:33:39: INFO: Looking for file 'system_16.img'
15:33:39: INFO: Looking for file 'system_17.img'
15:33:39: INFO: Looking for file 'system_18.img'
15:33:39: INFO: Looking for file 'system_19.img'
15:33:39: INFO: Looking for file 'system_20.img'
15:33:39: INFO: Looking for file 'system_21.img'
15:33:39: INFO: Looking for file 'system_22.img'
15:33:39: INFO: Looking for file 'system_23.img'
15:33:39: INFO: Looking for file 'system_24.img'
15:33:39: INFO: Looking for file 'system_25.img'
15:33:39: INFO: Looking for file 'system_26.img'
15:33:39: INFO: Looking for file 'system_27.img'
15:33:39: INFO: Looking for file 'system_28.img'
15:33:39: INFO: Looking for file 'system_29.img'
15:33:39: INFO: Looking for file 'system_30.img'
15:33:39: INFO: Looking for file 'system_31.img'
15:33:39: INFO: Looking for file 'system_32.img'
15:33:39: INFO: Looking for file 'system_33.img'
15:33:39: INFO: Looking for file 'system_34.img'
15:33:39: INFO: Looking for file 'system_35.img'
15:33:39: INFO: Looking for file 'system_36.img'
15:33:39: INFO: Looking for file 'system_37.img'
15:33:39: INFO: Looking for file 'system_38.img'
15:33:39: INFO: Looking for file 'system_39.img'
15:33:39: INFO: Looking for file 'system_40.img'
15:33:39: INFO: Looking for file 'system_41.img'
15:33:39: INFO: Looking for file 'system_42.img'
15:33:39: INFO: Looking for file 'system_43.img'
15:33:39: INFO: Looking for file 'system_44.img'
15:33:39: INFO: Looking for file 'system_45.img'
15:33:39: INFO: Looking for file 'vendor_1.img'
15:33:39: INFO: Looking for file 'vendor_2.img'
15:33:39: INFO: Looking for file 'vendor_3.img'
15:33:39: INFO: Looking for file 'vendor_4.img'
15:33:39: INFO: Looking for file 'vendor_5.img'
15:33:39: INFO: Looking for file 'vendor_6.img'
15:33:39: INFO: Looking for file 'vendor_7.img'
15:33:39: INFO: Looking for file 'vendor_8.img'
15:33:39: INFO: Looking for file 'vendor_9.img'
15:33:40: INFO: Looking for file 'vendor_10.img'
15:33:40: INFO: Looking for file 'vendor_11.img'
15:33:40: INFO: Looking for file 'boot.img'
15:33:40: INFO: Looking for file 'keymaster64.mbn'
15:33:40: INFO: Looking for file 'keymaster64.mbn'
15:33:40: INFO: Looking for file 'cmnlib.mbn'
15:33:40: INFO: Looking for file 'cmnlib64.mbn'
15:33:40: INFO: Looking for file 'cmnlib.mbn'
15:33:40: INFO: Looking for file 'cmnlib64.mbn'
15:33:40: INFO: Looking for file 'mdtpsecapp.mbn'
15:33:40: INFO: Looking for file 'mdtpsecapp.mbn'
15:33:40: INFO: Looking for file 'mdtp.img'
15:33:40: INFO: Looking for file 'mdtp.img'
15:33:40: INFO: Looking for file 'NON-HLOS.bin'
15:33:40: INFO: Looking for file 'dspso.bin'
15:33:40: INFO: Looking for file 'abl.elf'
15:33:40: INFO: Looking for file 'abl.elf'
15:33:40: INFO: Looking for file 'dp_AP_signed.mbn'
15:33:40: INFO: Looking for file 'dp_MSA_signed.mbn'
15:33:40: INFO: Looking for file 'sec.dat'
15:33:40: INFO: Looking for file 'BTFM.bin'
15:33:40: INFO: Looking for file 'BTFM.bin'
15:33:40: INFO: Looking for file 'devcfg.mbn'
15:33:40: INFO: Looking for file 'devcfg.mbn'
15:33:40: INFO: Looking for file 'asusfw.img'
15:33:40: INFO: Looking for file 'storsec.mbn'
15:33:40: INFO: Looking for file 'cache_1.img'
15:33:40: INFO: Looking for file 'cache_2.img'
15:33:40: INFO: Looking for file 'cache_3.img'
15:33:40: INFO: Looking for file 'cache_4.img'
15:33:40: INFO: Looking for file 'cache_5.img'
15:33:40: INFO: Looking for file 'recovery.img'
15:33:40: INFO: Looking for file 'APD.img'
15:33:40: INFO: Looking for file 'asdf.img'
15:33:40: INFO: Looking for file 'priv.img'
15:33:40: INFO: Looking for file 'version.img'
15:33:40: INFO: Looking for file 'userdata_1.img'
15:33:40: INFO: Looking for file 'userdata_2.img'
15:33:40: INFO: Looking for file 'userdata_3.img'
15:33:40: INFO: Looking for file 'userdata_4.img'
15:33:40: INFO: Looking for file 'userdata_5.img'
15:33:40: INFO: Looking for file 'userdata_6.img'
15:33:40: INFO: Looking for file 'userdata_7.img'
15:33:40: INFO: Looking for file 'userdata_8.img'
15:33:40: INFO: Looking for file 'userdata_9.img'
15:33:40: INFO: Looking for file 'userdata_10.img'
15:33:40: INFO: Looking for file 'userdata_11.img'
15:33:40: INFO: Looking for file 'userdata_12.img'
15:33:40: INFO: Looking for file 'userdata_13.img'
15:33:40: INFO: Looking for file 'userdata_14.img'
15:33:40: INFO: Looking for file 'userdata_15.img'
15:33:40: INFO: Looking for file 'userdata_16.img'
15:33:40: INFO: Looking for file 'userdata_17.img'
15:33:40: INFO: Looking for file 'userdata_18.img'
15:33:40: INFO: Looking for file 'userdata_19.img'
15:33:40: INFO: Looking for file 'userdata_20.img'
15:33:40: INFO: Looking for file 'userdata_21.img'
15:33:40: INFO: Looking for file 'userdata_22.img'
15:33:40: INFO: Looking for file 'userdata_23.img'
15:33:40: INFO: Looking for file 'userdata_24.img'
15:33:40: INFO: Looking for file 'userdata_25.img'
15:33:40: INFO: Looking for file 'userdata_26.img'
15:33:40: INFO: Looking for file 'userdata_27.img'
15:33:41: INFO: Looking for file 'userdata_28.img'
15:33:41: INFO: Looking for file 'userdata_29.img'
15:33:41: INFO: Looking for file 'userdata_30.img'
15:33:41: INFO: Looking for file 'userdata_31.img'
15:33:41: INFO: Looking for file 'userdata_32.img'
15:33:41: INFO: Looking for file 'userdata_33.img'
15:33:41: INFO: Looking for file 'userdata_34.img'
15:33:41: INFO: Looking for file 'userdata_35.img'
15:33:41: INFO: Looking for file 'userdata_36.img'
15:33:41: INFO: Looking for file 'userdata_37.img'
15:33:41: INFO: Looking for file 'userdata_38.img'
15:33:41: INFO: Looking for file 'userdata_39.img'
15:33:41: INFO: Looking for file 'userdata_40.img'
15:33:41: INFO: Looking for file 'userdata_41.img'
15:33:41: INFO: Looking for file 'userdata_42.img'
15:33:41: INFO: Looking for file 'userdata_43.img'
15:33:41: INFO: Looking for file 'userdata_44.img'
15:33:41: INFO: Looking for file 'userdata_45.img'
15:33:41: INFO: Looking for file 'userdata_46.img'
15:33:41: INFO: Looking for file 'userdata_47.img'
15:33:41: INFO: Looking for file 'userdata_48.img'
15:33:41: INFO: Looking for file 'userdata_49.img'
15:33:41: INFO: Looking for file 'userdata_50.img'
15:33:41: INFO: Looking for file 'userdata_51.img'
15:33:41: INFO: Looking for file 'userdata_52.img'
15:33:41: INFO: Looking for file 'userdata_53.img'
15:33:41: INFO: Looking for file 'userdata_54.img'
15:33:41: INFO: Looking for file 'userdata_55.img'
15:33:41: INFO: Looking for file 'userdata_56.img'
15:33:41: INFO: Looking for file 'userdata_57.img'
15:33:41: INFO: Looking for file 'userdata_58.img'
15:33:41: INFO: Looking for file 'userdata_59.img'
15:33:41: INFO: Looking for file 'userdata_60.img'
15:33:41: INFO: Looking for file 'userdata_61.img'
15:33:41: INFO: Looking for file 'userdata_62.img'
15:33:41: INFO: Looking for file 'userdata_63.img'
15:33:41: INFO: Looking for file 'userdata_64.img'
15:33:41: INFO: Looking for file 'userdata_65.img'
15:33:41: INFO: Looking for file 'userdata_66.img'
15:33:41: INFO: Looking for file 'userdata_67.img'
15:33:41: INFO: Looking for file 'userdata_68.img'
15:33:41: INFO: Looking for file 'userdata_69.img'
15:33:41: INFO: Looking for file 'userdata_70.img'
15:33:41: INFO: Looking for file 'userdata_71.img'
15:33:41: INFO: Looking for file 'userdata_72.img'
15:33:41: INFO: Looking for file 'userdata_73.img'
15:33:41: INFO: Looking for file 'userdata_74.img'
15:33:41: INFO: Looking for file 'userdata_75.img'
15:33:41: INFO: Looking for file 'userdata_76.img'
15:33:41: INFO: Looking for file 'userdata_77.img'
15:33:41: INFO: Looking for file 'userdata_78.img'
15:33:41: INFO: Looking for file 'userdata_79.img'
15:33:41: INFO: Looking for file 'userdata_80.img'
15:33:41: INFO: Looking for file 'userdata_81.img'
15:33:41: INFO: Looking for file 'gpt_main0.bin'
15:33:41: INFO: Looking for file 'gpt_backup0.bin'
15:33:41: INFO: 
Total to be tansferd with <program> or <read> is 2.78 GB
15:33:41: INFO: Sending <configure>
15:33:41: INFO: TARGET SAID: 'Binary build date: Dec  7 2018 @ 17:09:09'
15:33:41: INFO: TARGET SAID: 'Chip serial num: 4294438655 (0xfff7eeff)'
15:33:41: INFO: TARGET SAID: 'Supported Functions: program configure nop firmwarewrite patch setbootablestoragedrive ufs emmc power benchmark read getstorageinfo getsha256digest erase '
15:33:41: INFO: TARGET SAID: 'Calling usb_al_bulk_set_zlp_mode(TRUE) since ZlpAwareHost='1''
15:33:41: INFO: fh.attrs.MaxPayloadSizeToTargetInBytes = 49152
15:33:41: INFO: fh.attrs.MaxPayloadSizeToTargetInBytesSupported = 49152
15:33:41: INFO: In handleProgram('xbl.elf')
15:33:41: INFO: Looking for file 'xbl.elf'
15:33:41: INFO: =======================================================
15:33:41: INFO: {<program> FILE: 'D:\repair\HARD BRICK\[firmware27]ZB630KL_ZQL1820_Factory_201812071630_ChangeFlash\xbl.elf'}
15:33:41: INFO: {<program> (2.74 MB) 5606 sectors needed at location 131072 on LUN 0}
15:33:41: INFO: =======================================================
15:33:41: INFO: TARGET SAID: 'start 131072, num 5606'
15:33:41: INFO: Overall to target  0.140 seconds (19.55 MBps)
15:33:41: INFO: {percent files transferred   0.10%}
15:33:41: INFO: TARGET SAID: 'ERROR: SDCC Error 29 (3)'
15:33:41: INFO: TARGET SAID: 'ERROR: Write Failed sector 131072, size 96'
15:33:41: INFO: TARGET SAID: 'ERROR: Failed to write 1 slot 0, partition 131072, start_sector 96 num_sectors 0, error 3'
15:33:41: INFO: TARGET SAID: 'Finished programming start_sector 131168 and TotalSectorsToProgram 5606'
	 _____                    
	|  ___|                   
	| |__ _ __ _ __ ___  _ __ 
	|  __| '__| '__/ _ \| '__|
	| |__| |  | | | (_) | |   
	\____/_|  |_|  \___/|_|  
15:33:41: {ERROR: Please see log}
Writing log to 'C:\Users\jainikcomputers\AppData\Roaming\Qualcomm\QFIL\COMPORT_22\port_trace.txt', might take a minute
Log is 'C:\Users\jainikcomputers\AppData\Roaming\Qualcomm\QFIL\COMPORT_22\port_trace.txt'
Download Fail:FireHose Fail:FHLoader Fail:Process fail
Finish Download

**Comment by sileshn** [comment]
https://forum.xda-developers.com/showpost.php?s=14057dafde921b9042e82766d10cf2e8&p=79121501&postcount=22
